import re

SRC = "src/core/Akka.Streams/Dsl/SubFlowOperations.cs"
src = open(SRC, encoding="utf-8-sig").read()

def matched_angle(s, i):
    depth = 0
    for j in range(i, len(s)):
        if s[j] == '<': depth += 1
        elif s[j] == '>':
            depth -= 1
            if depth == 0: return j
    return -1

def split_top(s):
    parts, depth, cur = [], 0, ''
    for c in s:
        if c in '<([': depth += 1
        elif c in '>)]': depth -= 1
        if c == ',' and depth == 0:
            parts.append(cur); cur = ''
        else:
            cur += c
    if cur.strip(): parts.append(cur)
    return parts

def first_paren(s):
    ang = 0
    for i, c in enumerate(s):
        if c == '<': ang += 1
        elif c == '>': ang -= 1
        elif c == '(' and ang == 0: return i
    return -1

def matched_paren(s, i):
    depth = 0
    for j in range(i, len(s)):
        c = s[j]
        if c == '<': pass
        if c == '(': depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0: return j
    return -1

def split_ret_name(head):
    ang = 0; last = -1
    for i, c in enumerate(head):
        if c == '<': ang += 1
        elif c == '>': ang -= 1
        elif c == ' ' and ang == 0: last = i
    return head[:last].strip(), head[last+1:].strip()

def repl_subflow(s, kind):
    out, i = '', 0
    while i < len(s):
        if s.startswith('SubFlow<', i):
            j = matched_angle(s, i + 7)              # '<' is at i+7
            inner = s[i+8:j]
            first = split_top(inner)[0].strip()
            out += (f'SourceSubFlow<{first}, TMat>' if kind == 'source'
                    else f'FlowSubFlow<TFlowIn, {first}, TMat>')
            i = j + 1
        else:
            out += s[i]; i += 1
    return out

methods = []
for m in re.finditer(r'\n        public static ', src):
    start = m.end()
    arrow = src.find('=>', start)
    brace = src.find('\n        {', start)
    cand = [p for p in (arrow, brace) if p != -1]
    sig = ' '.join(src[start:min(cand)].split())
    methods.append(sig)

skipped = []
def emit(kind):
    out = []
    for sig in methods:
        if 'SubFlow<' not in sig:
            skipped.append(sig[:60]); continue
        po = first_paren(sig)
        head = sig[:po].strip()
        pc = matched_paren(sig, po)
        params = sig[po+1:pc]
        tail = sig[pc+1:].strip()                    # where-constraints
        ret, namegen = split_ret_name(head)
        if 'SubFlow<' not in ret:
            skipped.append(sig[:60]); continue
        ri = ret.index('SubFlow<')
        rargs = split_top(ret[ri+8:matched_angle(ret, ri+7)])
        if len(rargs) >= 2 and rargs[1].strip() != 'TMat':
            skipped.append('MAT:' + sig[:50]); continue
        if '<' in namegen:
            name = namegen[:namegen.index('<')]
            gens = split_top(namegen[namegen.index('<')+1:namegen.rindex('>')])
        else:
            name, gens = namegen, []
        gens = [g.strip() for g in gens if g.strip() != 'TClosed']
        gens = (['TFlowIn'] + gens) if kind == 'flow' else gens
        ret_t = repl_subflow(ret, kind)
        params_t = repl_subflow(params, kind)
        parts = split_top(params)
        recv = parts[0].strip().split()[-1]
        args = [recv] + [p.split('=')[0].strip().split()[-1] for p in parts[1:]]
        gen_s = ', '.join(gens)
        cons = (' ' + tail) if tail else ''
        out.append(
            f'        public static {ret_t} {name}<{gen_s}>({params_t}){cons} =>\n'
            f'            ({ret_t})SubFlowOperations.{name}({", ".join(args)});\n')
    return out

HEADER = '''//-----------------------------------------------------------------------
// <copyright file="{fn}" company="Akka.NET Project">
//     Copyright (C) 2009-2022 Lightbend Inc. <http://www.lightbend.com>
//     Copyright (C) 2013-2025 .NET Foundation <https://github.com/akkadotnet/akka.net>
// </copyright>
//-----------------------------------------------------------------------

// NOTE: Mirrors SubFlowOperations for {cls} so the concrete {root}-rooted substream type survives
// operator chaining (akka.net issue #5381). Each operator delegates to the base SubFlowOperations and
// re-narrows the result to {cls}; the cast is sound because the decorator's Via preserves the runtime
// type. Materialized-value-changing operators (AlsoToMaterialized, DivertToMaterialized,
// WatchTermination, InterleaveMaterialized, MergeMaterialized) are intentionally omitted: they cannot
// be expressed by the fixed-TClosed subtype and already throw on substreams (ViaMaterialized). Use the
// base SubFlowOperations for those. Generated by tools: gen_subflow_ops.py.

#pragma warning disable CS1591 // mirror of an already-documented surface
#pragma warning disable CS0618 // a few base operators are [Obsolete]; the typed mirror delegates to them

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Akka.Event;
using Akka.IO;
using Akka.Streams.Stage;
using Akka.Streams.Supervision;
using Akka.Util;

namespace Akka.Streams.Dsl
{{
    /// <summary>{cls}-typed mirrors of <see cref="SubFlowOperations"/> (issue #5381).</summary>
    public static class {cls}
    {{
'''

for kind, cls, root, fn in [
    ('source', 'SourceSubFlowOperations', 'Source', 'SourceSubFlowOperations.cs'),
    ('flow', 'FlowSubFlowOperations', 'Flow', 'FlowSubFlowOperations.cs')]:
    body = emit(kind)
    text = HEADER.format(fn=fn, cls=cls, root=root) + '\n'.join(body) + '    }\n}\n'
    open(f"src/core/Akka.Streams/Dsl/{fn}", "w", encoding="utf-8-sig", newline='\r\n').write(text)
    print(f"{fn}: {len(body)} methods")

print("skipped:", len(set(skipped)), sorted(set(skipped)))
