//-----------------------------------------------------------------------
// <copyright file="FlowSubFlowOperations.cs" company="Akka.NET Project">
//     Copyright (C) 2009-2022 Lightbend Inc. <http://www.lightbend.com>
//     Copyright (C) 2013-2025 .NET Foundation <https://github.com/akkadotnet/akka.net>
// </copyright>
//-----------------------------------------------------------------------

// NOTE: Mirrors SubFlowOperations for FlowSubFlowOperations so the concrete Flow-rooted substream type survives
// operator chaining (akka.net issue #5381). Each operator delegates to the base SubFlowOperations and
// re-narrows the result to FlowSubFlowOperations; the cast is sound because the decorator's Via preserves the runtime
// type. Materialized-value-changing operators (AlsoToMaterialized, DivertToMaterialized,
// WatchTermination, InterleaveMaterialized, MergeMaterialized) are intentionally omitted: they cannot
// be expressed by the fixed-TClosed subtype and already throw on substreams (ViaMaterialized). Use the
// base SubFlowOperations for those. Generated by tools: gen_subflow_ops.py.

#pragma warning disable CS1591 // mirror of an already-documented surface
#pragma warning disable CS0618 // a few base operators are [Obsolete]; the typed mirror delegates to them

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Akka.Event;
using Akka.IO;
using Akka.Streams.Stage;
using Akka.Streams.Supervision;
using Akka.Util;

namespace Akka.Streams.Dsl
{
    /// <summary>FlowSubFlowOperations-typed mirrors of <see cref="SubFlowOperations"/> (issue #5381).</summary>
    public static class FlowSubFlowOperations
    {
        public static FlowSubFlow<TFlowIn, Option<TOut>, TMat> Recover<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Func<Exception, Option<TOut>> partialFunc) =>
            (FlowSubFlow<TFlowIn, Option<TOut>, TMat>)SubFlowOperations.Recover(flow, partialFunc);

        public static FlowSubFlow<TFlowIn, TOut, TMat> RecoverWith<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Func<Exception, IGraph<SourceShape<TOut>, TMat>> partialFunc) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.RecoverWith(flow, partialFunc);

        public static FlowSubFlow<TFlowIn, TOut, TMat> RecoverWithRetries<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Func<Exception, IGraph<SourceShape<TOut>, TMat>> partialFunc, int attempts) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.RecoverWithRetries(flow, partialFunc, attempts);

        public static FlowSubFlow<TFlowIn, TOut, TMat> SelectError<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Func<Exception, Exception> selector) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.SelectError(flow, selector);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Select<TFlowIn, TIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TIn, TMat> flow, Func<TIn, TOut> mapper) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Select(flow, mapper);

        public static FlowSubFlow<TFlowIn, TOut, TMat> WireTap<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Action<TOut> action) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.WireTap(flow, action);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> SelectMany<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, Func<TOut1, IEnumerable<TOut2>> mapConcater) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.SelectMany(flow, mapConcater);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> StatefulSelectMany<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, Func<Func<TOut1, IEnumerable<TOut2>>> mapConcaterFactory) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.StatefulSelectMany(flow, mapConcaterFactory);

        public static FlowSubFlow<TFlowIn, TOut, TMat> SelectAsync<TFlowIn, TIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TIn, TMat> flow, int parallelism, Func<TIn, Task<TOut>> asyncMapper) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.SelectAsync(flow, parallelism, asyncMapper);

        public static FlowSubFlow<TFlowIn, TOut, TMat> SelectAsyncUnordered<TFlowIn, TIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TIn, TMat> flow, int parallelism, Func<TIn, Task<TOut>> asyncMapper) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.SelectAsyncUnordered(flow, parallelism, asyncMapper);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Where<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Predicate<TOut> predicate) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Where(flow, predicate);

        public static FlowSubFlow<TFlowIn, TOut, TMat> WhereNot<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Predicate<TOut> predicate) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.WhereNot(flow, predicate);

        public static FlowSubFlow<TFlowIn, TOut, TMat> TakeWhile<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Predicate<TOut> predicate, bool inclusive = false) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.TakeWhile(flow, predicate, inclusive);

        public static FlowSubFlow<TFlowIn, TOut, TMat> SkipWhile<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Predicate<TOut> predicate) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.SkipWhile(flow, predicate);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Collect<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, Func<TOut1, TOut2> collector) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Collect(flow, collector);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Collect<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, Func<TOut1, bool>? isDefined, Func<TOut1, TOut2> collector) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Collect(flow, isDefined, collector);

        public static FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat> Grouped<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, int n) =>
            (FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat>)SubFlowOperations.Grouped(flow, n);

        public static FlowSubFlow<TFlowIn, T, TMat> Limit<TFlowIn, T, TMat>(this FlowSubFlow<TFlowIn, T, TMat> flow, long max) =>
            (FlowSubFlow<TFlowIn, T, TMat>)SubFlowOperations.Limit(flow, max);

        public static FlowSubFlow<TFlowIn, T, TMat> LimitWeighted<TFlowIn, T, TMat>(this FlowSubFlow<TFlowIn, T, TMat> flow, long max, Func<T, long> costFunc) =>
            (FlowSubFlow<TFlowIn, T, TMat>)SubFlowOperations.LimitWeighted(flow, max, costFunc);

        public static FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat> Sliding<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, int n, int step = 1) =>
            (FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat>)SubFlowOperations.Sliding(flow, n, step);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Scan<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, TOut2 zero, Func<TOut2, TOut1, TOut2> scan) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Scan(flow, zero, scan);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> ScanAsync<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, TOut2 zero, Func<TOut2, TOut1, Task<TOut2>> scan) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.ScanAsync(flow, zero, scan);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Aggregate<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, TOut2 zero, Func<TOut2, TOut1, TOut2> fold) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Aggregate(flow, zero, fold);

        public static FlowSubFlow<TFlowIn, TOut, TMat> AggregateAsync<TFlowIn, TIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TIn, TMat> flow, TOut zero, Func<TOut, TIn, Task<TOut>> fold) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.AggregateAsync(flow, zero, fold);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Sum<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Func<TOut, TOut, TOut> reduce) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Sum(flow, reduce);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Intersperse<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TOut start, TOut inject, TOut end) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Intersperse(flow, start, inject, end);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Intersperse<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TOut inject) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Intersperse(flow, inject);

        public static FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat> GroupedWithin<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, int n, TimeSpan timeout) =>
            (FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat>)SubFlowOperations.GroupedWithin(flow, n, timeout);

        public static FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat> GroupedWeightedWithin<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, long maxWeight, int maxNumber, TimeSpan interval, Func<TOut, long> costFn) =>
            (FlowSubFlow<TFlowIn, IEnumerable<TOut>, TMat>)SubFlowOperations.GroupedWeightedWithin(flow, maxWeight, maxNumber, interval, costFn);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Delay<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan of, DelayOverflowStrategy? strategy = null) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Delay(flow, of, strategy);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Skip<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, long n) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Skip(flow, n);

        public static FlowSubFlow<TFlowIn, TOut, TMat> SkipWithin<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan duration) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.SkipWithin(flow, duration);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Take<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, long n) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Take(flow, n);

        public static FlowSubFlow<TFlowIn, TOut, TMat> TakeWithin<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan duration) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.TakeWithin(flow, duration);

        public static FlowSubFlow<TFlowIn, TSeed, TMat> ConflateWithSeed<TFlowIn, TOut, TMat, TSeed>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Func<TOut, TSeed> seed, Func<TSeed, TOut, TSeed> aggregate) =>
            (FlowSubFlow<TFlowIn, TSeed, TMat>)SubFlowOperations.ConflateWithSeed(flow, seed, aggregate);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Conflate<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, Func<TOut, TOut, TOut> aggregate) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Conflate(flow, aggregate);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Batch<TFlowIn, TOut, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, long max, Func<TOut, TOut2> seed, Func<TOut2, TOut, TOut2> aggregate) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Batch(flow, max, seed, aggregate);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> BatchWeighted<TFlowIn, TOut, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, long max, Func<TOut, long> costFunction, Func<TOut, TOut2> seed, Func<TOut2, TOut, TOut2> aggregate) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.BatchWeighted(flow, max, costFunction, seed, aggregate);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Expand<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, Func<TOut1, IEnumerator<TOut2>> extrapolate) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Expand(flow, extrapolate);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Buffer<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, int size, OverflowStrategy strategy) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Buffer(flow, size, strategy);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Transform<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, Func<IStage<TOut1, TOut2>> stageFactory) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Transform(flow, stageFactory);

        public static FlowSubFlow<TFlowIn, (IImmutableList<TOut>, Source<TOut, NotUsed>), TMat> PrefixAndTail<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, int n) =>
            (FlowSubFlow<TFlowIn, (IImmutableList<TOut>, Source<TOut, NotUsed>), TMat>)SubFlowOperations.PrefixAndTail(flow, n);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> ConcatMany<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, Func<TOut1, IGraph<SourceShape<TOut2>, TMat>> flatten) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.ConcatMany(flow, flatten);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> MergeMany<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, int breadth, Func<TOut1, IGraph<SourceShape<TOut2>, TMat>> flatten) =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.MergeMany(flow, breadth, flatten);

        public static FlowSubFlow<TFlowIn, (TOut1, long), TMat> ZipWithIndex<TFlowIn, TOut1, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow) =>
            (FlowSubFlow<TFlowIn, (TOut1, long), TMat>)SubFlowOperations.ZipWithIndex(flow);

        public static FlowSubFlow<TFlowIn, TOut, TMat> InitialTimeout<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan timeout) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.InitialTimeout(flow, timeout);

        public static FlowSubFlow<TFlowIn, TOut, TMat> CompletionTimeout<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan timeout) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.CompletionTimeout(flow, timeout);

        public static FlowSubFlow<TFlowIn, TOut, TMat> IdleTimeout<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan timeout) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.IdleTimeout(flow, timeout);

        public static FlowSubFlow<TFlowIn, TOut, TMat> BackpressureTimeout<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan timeout) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.BackpressureTimeout(flow, timeout);

        public static FlowSubFlow<TFlowIn, TInjected, TMat> KeepAlive<TFlowIn, TOut, TInjected, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan timeout, Func<TInjected> injectElement) where TOut : TInjected =>
            (FlowSubFlow<TFlowIn, TInjected, TMat>)SubFlowOperations.KeepAlive(flow, timeout, injectElement);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Throttle<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, int elements, TimeSpan per, int maximumBurst, ThrottleMode mode) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Throttle(flow, elements, per, maximumBurst, mode);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Throttle<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, int cost, TimeSpan per, int maximumBurst, Func<TOut, int> calculateCost, ThrottleMode mode) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Throttle(flow, cost, per, maximumBurst, calculateCost, mode);

        public static FlowSubFlow<TFlowIn, TOut, TMat> AlsoTo<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.AlsoTo(flow, that);

        public static FlowSubFlow<TFlowIn, TOut, TMat> AlsoTo<TFlowIn, TOut, TMat>( this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that, bool propagateFailure) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.AlsoTo(flow, that, propagateFailure);

        public static FlowSubFlow<TFlowIn, TOut, TMat> WireTap<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.WireTap(flow, that);

        public static FlowSubFlow<TFlowIn, TOut, TMat> DivertTo<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that, Func<TOut, bool> when) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.DivertTo(flow, that, when);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Detach<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Detach(flow);

        public static FlowSubFlow<TFlowIn, TOut, TMat> InitialDelay<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, TimeSpan delay) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.InitialDelay(flow, delay);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Log<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, string name, Func<TOut, object> extract = null, ILoggingAdapter log = null) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Log(flow, name, extract, log);

        public static FlowSubFlow<TFlowIn, (T1, T2), TMat> Zip<TFlowIn, T1, T2, TMat>(this FlowSubFlow<TFlowIn, T1, TMat> flow, IGraph<SourceShape<T2>, TMat> other) =>
            (FlowSubFlow<TFlowIn, (T1, T2), TMat>)SubFlowOperations.Zip(flow, other);

        public static FlowSubFlow<TFlowIn, T3, TMat> ZipWith<TFlowIn, T1, T2, T3, TMat>(this FlowSubFlow<TFlowIn, T1, TMat> flow, IGraph<SourceShape<T2>, TMat> other, Func<T1, T2, T3> combine) =>
            (FlowSubFlow<TFlowIn, T3, TMat>)SubFlowOperations.ZipWith(flow, other, combine);

        public static FlowSubFlow<TFlowIn, T2, TMat> Interleave<TFlowIn, T1, T2, TMat>(this FlowSubFlow<TFlowIn, T1, TMat> flow, IGraph<SourceShape<T2>, TMat> other, int segmentSize) where T1 : T2 =>
            (FlowSubFlow<TFlowIn, T2, TMat>)SubFlowOperations.Interleave(flow, other, segmentSize);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Merge<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, IGraph<SourceShape<TOut2>, TMat> other, bool eagerComplete = false) where TOut1 : TOut2 =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Merge(flow, other, eagerComplete);

        public static FlowSubFlow<TFlowIn, TOut, TMat> MergeSorted<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other, Func<TOut, TOut, int> orderFunc) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.MergeSorted(flow, other, orderFunc);

        public static FlowSubFlow<TFlowIn, TOut, TMat> MergeSorted<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other) where TOut : IComparable<TOut> =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.MergeSorted(flow, other);

        public static FlowSubFlow<TFlowIn, TOut, TMat> MergeSorted<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other, IComparer<TOut> comparer) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.MergeSorted(flow, other, comparer);

        public static FlowSubFlow<TFlowIn, TOut, TMat> Concat<TFlowIn, TOut, TMat>(this FlowSubFlow<TFlowIn, TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other) =>
            (FlowSubFlow<TFlowIn, TOut, TMat>)SubFlowOperations.Concat(flow, other);

        public static FlowSubFlow<TFlowIn, TOut2, TMat> Prepend<TFlowIn, TOut1, TOut2, TMat>(this FlowSubFlow<TFlowIn, TOut1, TMat> flow, IGraph<SourceShape<TOut2>, TMat> that) where TOut1 : TOut2 =>
            (FlowSubFlow<TFlowIn, TOut2, TMat>)SubFlowOperations.Prepend(flow, that);

        public static FlowSubFlow<TFlowIn, T, TMat> OrElse<TFlowIn, T, TMat>(this FlowSubFlow<TFlowIn, T, TMat> flow, IGraph<SourceShape<T>, TMat> secondary) =>
            (FlowSubFlow<TFlowIn, T, TMat>)SubFlowOperations.OrElse(flow, secondary);
    }
}
