//-----------------------------------------------------------------------
// <copyright file="SourceSubFlowOperations.cs" company="Akka.NET Project">
//     Copyright (C) 2009-2022 Lightbend Inc. <http://www.lightbend.com>
//     Copyright (C) 2013-2025 .NET Foundation <https://github.com/akkadotnet/akka.net>
// </copyright>
//-----------------------------------------------------------------------

// NOTE: Mirrors SubFlowOperations for SourceSubFlowOperations so the concrete Source-rooted substream type survives
// operator chaining (akka.net issue #5381). Each operator delegates to the base SubFlowOperations and
// re-narrows the result to SourceSubFlowOperations; the cast is sound because the decorator's Via preserves the runtime
// type. Materialized-value-changing operators (AlsoToMaterialized, DivertToMaterialized,
// WatchTermination, InterleaveMaterialized, MergeMaterialized) are intentionally omitted: they cannot
// be expressed by the fixed-TClosed subtype and already throw on substreams (ViaMaterialized). Use the
// base SubFlowOperations for those. Generated by tools: gen_subflow_ops.py.

#pragma warning disable CS1591 // mirror of an already-documented surface
#pragma warning disable CS0618 // a few base operators are [Obsolete]; the typed mirror delegates to them

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Akka.Event;
using Akka.IO;
using Akka.Streams.Stage;
using Akka.Streams.Supervision;
using Akka.Util;

namespace Akka.Streams.Dsl
{
    /// <summary>SourceSubFlowOperations-typed mirrors of <see cref="SubFlowOperations"/> (issue #5381).</summary>
    public static class SourceSubFlowOperations
    {
        public static SourceSubFlow<Option<TOut>, TMat> Recover<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Func<Exception, Option<TOut>> partialFunc) =>
            (SourceSubFlow<Option<TOut>, TMat>)SubFlowOperations.Recover(flow, partialFunc);

        public static SourceSubFlow<TOut, TMat> RecoverWith<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Func<Exception, IGraph<SourceShape<TOut>, TMat>> partialFunc) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.RecoverWith(flow, partialFunc);

        public static SourceSubFlow<TOut, TMat> RecoverWithRetries<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Func<Exception, IGraph<SourceShape<TOut>, TMat>> partialFunc, int attempts) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.RecoverWithRetries(flow, partialFunc, attempts);

        public static SourceSubFlow<TOut, TMat> SelectError<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Func<Exception, Exception> selector) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.SelectError(flow, selector);

        public static SourceSubFlow<TOut, TMat> Select<TIn, TOut, TMat>(this SourceSubFlow<TIn, TMat> flow, Func<TIn, TOut> mapper) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Select(flow, mapper);

        public static SourceSubFlow<TOut, TMat> WireTap<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Action<TOut> action) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.WireTap(flow, action);

        public static SourceSubFlow<TOut2, TMat> SelectMany<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, Func<TOut1, IEnumerable<TOut2>> mapConcater) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.SelectMany(flow, mapConcater);

        public static SourceSubFlow<TOut2, TMat> StatefulSelectMany<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, Func<Func<TOut1, IEnumerable<TOut2>>> mapConcaterFactory) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.StatefulSelectMany(flow, mapConcaterFactory);

        public static SourceSubFlow<TOut, TMat> SelectAsync<TIn, TOut, TMat>(this SourceSubFlow<TIn, TMat> flow, int parallelism, Func<TIn, Task<TOut>> asyncMapper) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.SelectAsync(flow, parallelism, asyncMapper);

        public static SourceSubFlow<TOut, TMat> SelectAsyncUnordered<TIn, TOut, TMat>(this SourceSubFlow<TIn, TMat> flow, int parallelism, Func<TIn, Task<TOut>> asyncMapper) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.SelectAsyncUnordered(flow, parallelism, asyncMapper);

        public static SourceSubFlow<TOut, TMat> Where<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Predicate<TOut> predicate) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Where(flow, predicate);

        public static SourceSubFlow<TOut, TMat> WhereNot<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Predicate<TOut> predicate) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.WhereNot(flow, predicate);

        public static SourceSubFlow<TOut, TMat> TakeWhile<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Predicate<TOut> predicate, bool inclusive = false) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.TakeWhile(flow, predicate, inclusive);

        public static SourceSubFlow<TOut, TMat> SkipWhile<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Predicate<TOut> predicate) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.SkipWhile(flow, predicate);

        public static SourceSubFlow<TOut2, TMat> Collect<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, Func<TOut1, TOut2> collector) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Collect(flow, collector);

        public static SourceSubFlow<TOut2, TMat> Collect<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, Func<TOut1, bool>? isDefined, Func<TOut1, TOut2> collector) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Collect(flow, isDefined, collector);

        public static SourceSubFlow<IEnumerable<TOut>, TMat> Grouped<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, int n) =>
            (SourceSubFlow<IEnumerable<TOut>, TMat>)SubFlowOperations.Grouped(flow, n);

        public static SourceSubFlow<T, TMat> Limit<T, TMat>(this SourceSubFlow<T, TMat> flow, long max) =>
            (SourceSubFlow<T, TMat>)SubFlowOperations.Limit(flow, max);

        public static SourceSubFlow<T, TMat> LimitWeighted<T, TMat>(this SourceSubFlow<T, TMat> flow, long max, Func<T, long> costFunc) =>
            (SourceSubFlow<T, TMat>)SubFlowOperations.LimitWeighted(flow, max, costFunc);

        public static SourceSubFlow<IEnumerable<TOut>, TMat> Sliding<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, int n, int step = 1) =>
            (SourceSubFlow<IEnumerable<TOut>, TMat>)SubFlowOperations.Sliding(flow, n, step);

        public static SourceSubFlow<TOut2, TMat> Scan<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, TOut2 zero, Func<TOut2, TOut1, TOut2> scan) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Scan(flow, zero, scan);

        public static SourceSubFlow<TOut2, TMat> ScanAsync<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, TOut2 zero, Func<TOut2, TOut1, Task<TOut2>> scan) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.ScanAsync(flow, zero, scan);

        public static SourceSubFlow<TOut2, TMat> Aggregate<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, TOut2 zero, Func<TOut2, TOut1, TOut2> fold) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Aggregate(flow, zero, fold);

        public static SourceSubFlow<TOut, TMat> AggregateAsync<TIn, TOut, TMat>(this SourceSubFlow<TIn, TMat> flow, TOut zero, Func<TOut, TIn, Task<TOut>> fold) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.AggregateAsync(flow, zero, fold);

        public static SourceSubFlow<TOut, TMat> Sum<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Func<TOut, TOut, TOut> reduce) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Sum(flow, reduce);

        public static SourceSubFlow<TOut, TMat> Intersperse<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TOut start, TOut inject, TOut end) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Intersperse(flow, start, inject, end);

        public static SourceSubFlow<TOut, TMat> Intersperse<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TOut inject) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Intersperse(flow, inject);

        public static SourceSubFlow<IEnumerable<TOut>, TMat> GroupedWithin<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, int n, TimeSpan timeout) =>
            (SourceSubFlow<IEnumerable<TOut>, TMat>)SubFlowOperations.GroupedWithin(flow, n, timeout);

        public static SourceSubFlow<IEnumerable<TOut>, TMat> GroupedWeightedWithin<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, long maxWeight, int maxNumber, TimeSpan interval, Func<TOut, long> costFn) =>
            (SourceSubFlow<IEnumerable<TOut>, TMat>)SubFlowOperations.GroupedWeightedWithin(flow, maxWeight, maxNumber, interval, costFn);

        public static SourceSubFlow<TOut, TMat> Delay<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan of, DelayOverflowStrategy? strategy = null) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Delay(flow, of, strategy);

        public static SourceSubFlow<TOut, TMat> Skip<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, long n) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Skip(flow, n);

        public static SourceSubFlow<TOut, TMat> SkipWithin<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan duration) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.SkipWithin(flow, duration);

        public static SourceSubFlow<TOut, TMat> Take<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, long n) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Take(flow, n);

        public static SourceSubFlow<TOut, TMat> TakeWithin<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan duration) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.TakeWithin(flow, duration);

        public static SourceSubFlow<TSeed, TMat> ConflateWithSeed<TOut, TMat, TSeed>(this SourceSubFlow<TOut, TMat> flow, Func<TOut, TSeed> seed, Func<TSeed, TOut, TSeed> aggregate) =>
            (SourceSubFlow<TSeed, TMat>)SubFlowOperations.ConflateWithSeed(flow, seed, aggregate);

        public static SourceSubFlow<TOut, TMat> Conflate<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, Func<TOut, TOut, TOut> aggregate) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Conflate(flow, aggregate);

        public static SourceSubFlow<TOut2, TMat> Batch<TOut, TOut2, TMat>(this SourceSubFlow<TOut, TMat> flow, long max, Func<TOut, TOut2> seed, Func<TOut2, TOut, TOut2> aggregate) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Batch(flow, max, seed, aggregate);

        public static SourceSubFlow<TOut2, TMat> BatchWeighted<TOut, TOut2, TMat>(this SourceSubFlow<TOut, TMat> flow, long max, Func<TOut, long> costFunction, Func<TOut, TOut2> seed, Func<TOut2, TOut, TOut2> aggregate) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.BatchWeighted(flow, max, costFunction, seed, aggregate);

        public static SourceSubFlow<TOut2, TMat> Expand<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, Func<TOut1, IEnumerator<TOut2>> extrapolate) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Expand(flow, extrapolate);

        public static SourceSubFlow<TOut, TMat> Buffer<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, int size, OverflowStrategy strategy) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Buffer(flow, size, strategy);

        public static SourceSubFlow<TOut2, TMat> Transform<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, Func<IStage<TOut1, TOut2>> stageFactory) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Transform(flow, stageFactory);

        public static SourceSubFlow<(IImmutableList<TOut>, Source<TOut, NotUsed>), TMat> PrefixAndTail<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, int n) =>
            (SourceSubFlow<(IImmutableList<TOut>, Source<TOut, NotUsed>), TMat>)SubFlowOperations.PrefixAndTail(flow, n);

        public static SourceSubFlow<TOut2, TMat> ConcatMany<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, Func<TOut1, IGraph<SourceShape<TOut2>, TMat>> flatten) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.ConcatMany(flow, flatten);

        public static SourceSubFlow<TOut2, TMat> MergeMany<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, int breadth, Func<TOut1, IGraph<SourceShape<TOut2>, TMat>> flatten) =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.MergeMany(flow, breadth, flatten);

        public static SourceSubFlow<(TOut1, long), TMat> ZipWithIndex<TOut1, TMat>(this SourceSubFlow<TOut1, TMat> flow) =>
            (SourceSubFlow<(TOut1, long), TMat>)SubFlowOperations.ZipWithIndex(flow);

        public static SourceSubFlow<TOut, TMat> InitialTimeout<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan timeout) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.InitialTimeout(flow, timeout);

        public static SourceSubFlow<TOut, TMat> CompletionTimeout<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan timeout) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.CompletionTimeout(flow, timeout);

        public static SourceSubFlow<TOut, TMat> IdleTimeout<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan timeout) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.IdleTimeout(flow, timeout);

        public static SourceSubFlow<TOut, TMat> BackpressureTimeout<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan timeout) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.BackpressureTimeout(flow, timeout);

        public static SourceSubFlow<TInjected, TMat> KeepAlive<TOut, TInjected, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan timeout, Func<TInjected> injectElement) where TOut : TInjected =>
            (SourceSubFlow<TInjected, TMat>)SubFlowOperations.KeepAlive(flow, timeout, injectElement);

        public static SourceSubFlow<TOut, TMat> Throttle<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, int elements, TimeSpan per, int maximumBurst, ThrottleMode mode) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Throttle(flow, elements, per, maximumBurst, mode);

        public static SourceSubFlow<TOut, TMat> Throttle<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, int cost, TimeSpan per, int maximumBurst, Func<TOut, int> calculateCost, ThrottleMode mode) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Throttle(flow, cost, per, maximumBurst, calculateCost, mode);

        public static SourceSubFlow<TOut, TMat> AlsoTo<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.AlsoTo(flow, that);

        public static SourceSubFlow<TOut, TMat> AlsoTo<TOut, TMat>( this SourceSubFlow<TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that, bool propagateFailure) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.AlsoTo(flow, that, propagateFailure);

        public static SourceSubFlow<TOut, TMat> WireTap<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.WireTap(flow, that);

        public static SourceSubFlow<TOut, TMat> DivertTo<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, IGraph<SinkShape<TOut>, TMat> that, Func<TOut, bool> when) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.DivertTo(flow, that, when);

        public static SourceSubFlow<TOut, TMat> Detach<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Detach(flow);

        public static SourceSubFlow<TOut, TMat> InitialDelay<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, TimeSpan delay) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.InitialDelay(flow, delay);

        public static SourceSubFlow<TOut, TMat> Log<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, string name, Func<TOut, object> extract = null, ILoggingAdapter log = null) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Log(flow, name, extract, log);

        public static SourceSubFlow<(T1, T2), TMat> Zip<T1, T2, TMat>(this SourceSubFlow<T1, TMat> flow, IGraph<SourceShape<T2>, TMat> other) =>
            (SourceSubFlow<(T1, T2), TMat>)SubFlowOperations.Zip(flow, other);

        public static SourceSubFlow<T3, TMat> ZipWith<T1, T2, T3, TMat>(this SourceSubFlow<T1, TMat> flow, IGraph<SourceShape<T2>, TMat> other, Func<T1, T2, T3> combine) =>
            (SourceSubFlow<T3, TMat>)SubFlowOperations.ZipWith(flow, other, combine);

        public static SourceSubFlow<T2, TMat> Interleave<T1, T2, TMat>(this SourceSubFlow<T1, TMat> flow, IGraph<SourceShape<T2>, TMat> other, int segmentSize) where T1 : T2 =>
            (SourceSubFlow<T2, TMat>)SubFlowOperations.Interleave(flow, other, segmentSize);

        public static SourceSubFlow<TOut2, TMat> Merge<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, IGraph<SourceShape<TOut2>, TMat> other, bool eagerComplete = false) where TOut1 : TOut2 =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Merge(flow, other, eagerComplete);

        public static SourceSubFlow<TOut, TMat> MergeSorted<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other, Func<TOut, TOut, int> orderFunc) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.MergeSorted(flow, other, orderFunc);

        public static SourceSubFlow<TOut, TMat> MergeSorted<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other) where TOut : IComparable<TOut> =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.MergeSorted(flow, other);

        public static SourceSubFlow<TOut, TMat> MergeSorted<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other, IComparer<TOut> comparer) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.MergeSorted(flow, other, comparer);

        public static SourceSubFlow<TOut, TMat> Concat<TOut, TMat>(this SourceSubFlow<TOut, TMat> flow, IGraph<SourceShape<TOut>, TMat> other) =>
            (SourceSubFlow<TOut, TMat>)SubFlowOperations.Concat(flow, other);

        public static SourceSubFlow<TOut2, TMat> Prepend<TOut1, TOut2, TMat>(this SourceSubFlow<TOut1, TMat> flow, IGraph<SourceShape<TOut2>, TMat> that) where TOut1 : TOut2 =>
            (SourceSubFlow<TOut2, TMat>)SubFlowOperations.Prepend(flow, that);

        public static SourceSubFlow<T, TMat> OrElse<T, TMat>(this SourceSubFlow<T, TMat> flow, IGraph<SourceShape<T>, TMat> secondary) =>
            (SourceSubFlow<T, TMat>)SubFlowOperations.OrElse(flow, secondary);
    }
}
